# Generated by Django 3.0.3 on 2020-05-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platter',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dinner_platter',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small',
            field=models.FloatField(),
        ),
    ]
